name: Inject redirect-origin Service Worker to static website
description: Redirect requests of origin to another given base URL.
branding:
  icon: corner-up-right
  color: purple
inputs:
  www-root:
    description:
    required: true
  target-base-url:
    description:
    required: true
  http-404-page:
    description:
    default: ""
  service-worker-filename:
    description:
    default: sw.js
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "::group::Resolve www root full path"

        # Since we'll run `cd`
        WWW_ROOT="$(realpath "$WWW_ROOT")"
        echo "$WWW_ROOT"

        echo "::endgroup"

        echo "::group::Install dependencies"

        cd "$ACTION_PATH"
        yarn

        echo "::endgroup"

        echo "::group::Run inject"

        yarn inject "$WWW_ROOT" "$TARGET_BASE_URL" "$HTTP_404_PAGE" "$SERVICE_WORKER_FILENAME"

        echo "::endgroup"
      env:
        ACTION_PATH: ${{ github.action_path }}
        WWW_ROOT: ${{ inputs.www-root }}
        TARGET_BASE_URL: ${{ inputs.target-base-url }}
        HTTP_404_PAGE: ${{ inputs.http-404-page }}
        SERVICE_WORKER_FILENAME: ${{ inputs.service-worker-filename }}
